spring:
  application:
    name: clinic

  data:
    mongodb:
      uri: ${DB_URL:mongodb://localhost:27017/clinic_db}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

external:
  pharmacy:
    url: ${PHARMACY_URL:http://localhost:8081}